version: "3.0"
services:
  container_mysql:
    image: mysql 
    environment:
      MYSQL_DATABASE: "casadocodigo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  container_casadocodigo:
    image: casadocodigo:v1-dev
    environment:
      USUARIO: "root"
      SENHA: ""
      JDBC_CONNECTION_STRING: "jdbc:mysql://container_mysql:3306/casadocodigo"
      TZ: America/Sao_Paulo
    depends_on:
      - container_mysql
  
  container_nginx:
    image: nginx_casadocodigo:v1-dev
    ports:
      - 80:80
    depends_on:
      - container_casadocodigo